# These workflows have been nicked from https://github.com/influxdata/grafana-flightsql-datasource
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # All nested workflows will inherit these permissions and so no need to declare
  # in each step file
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/step_build.yml

  e2e-tests:
    needs: [build]
    uses: ./.github/workflows/step_e2e-tests.yml

  package:
    needs: [build, e2e-tests]
    uses: ./.github/workflows/step_package.yml
    # For nightly build releases
    permissions:
      contents: write
