name: build
run-name: Build and Unit Tests

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Remove tools directory
        run: rm -rf tools

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Check types
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test:ci

      - name: Build frontend
        run: yarn build

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      # Install chrome as we will use it in e2e tests
      - uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
        with:
          install-dependencies: true

      - name: Start headless chrome for remote tests
        run: >-
          chrome
          --remote-debugging-port=44251
          --no-sandbox
          --disable-gpu
          --no-first-run
          --no-default-browser-check
          --headless
          --hide-scrollbars
          --mute-audio
          --disable-background-networking
          --enable-features=NetworkService,NetworkServiceInProcess
          --disable-background-timer-throttling
          --disable-backgrounding-occluded-windows
          --disable-breakpad
          --disable-client-side-phishing-detection
          --disable-default-apps
          --disable-dev-shm-usage
          --disable-extensions
          --disable-features=site-per-process,Translate,BlinkGenPropertyTrees
          --disable-hang-monitor
          --disable-ipc-flooding-protection
          --disable-popup-blocking
          --disable-prompt-on-repost
          --disable-renderer-backgrounding
          --disable-sync
          --force-color-profile=srgb
          --metrics-recording-only
          --safebrowsing-disable-auto-update
          --enable-automation
          --password-store=basic
          --use-mock-keychain &
          
          echo "CHROME_REMOTE_URL=ws://localhost:44251" >> $GITHUB_ENV

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.23'

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@6a5dcb5fe61f43d7c08a98bc3cf9bc63c308c08e # v3
        with:
          version: latest
          args: coverage

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@6a5dcb5fe61f43d7c08a98bc3cf9bc63c308c08e # v3
        with:
          version: latest
          args: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: build-artifacts
          path: dist
          retention-days: 1
