name: e2e-tests
run-name: End2End tests

on:
  workflow_call:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Grafana v10
          #- grafana-version: 10.4.5
          #  remote-chrome-url: ''
          #  snapshots-folder: local-chrome

          # Grafana v11
          - grafana-version: 11.1.0
            remote-chrome-url: ws://localhost:9222
            snapshots-folder: remote-chrome

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download build artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build-artifacts
          path: dist

      - name: Setup Node.js environment
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      # Install chrome as we will use it in e2e tests
      - name: Install browsers
        run: yarn playwright install

      - name: Run e2e tests
        env:
          GRAFANA_VERSION: ${{ matrix.grafana-version }}
          GF_REPORTER_PLUGIN_REMOTE_CHROME_URL: ${{ matrix.remote-chrome-url }}
        run: |
          # Upload/Download artifacts wont preserve permissions
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
          # Add +x bits on executables
          chmod -R +x dist/gpx_*
 
          # Start containers
          yarn e2e:server:up

          # Sleep for a while for containers to be up and running
          sleep 20

          # Run e2e tests
          yarn e2e

          # Run API tests
          yarn e2e:report

          # yarn e2e:server:down

      - name: Compare PDF report from plain server
        uses: nowsprinting/diff-pdf-action@2370f6da4625b181e29e0aedaae32fcaa67064f9 # v1.2.1
        with:
          file1: default.pdf
          file2: .ci/reports/default.pdf
          options: --verbose --output-diff=default-diff.pdf
      
      - name: Compare PDF report from TLS server
        uses: nowsprinting/diff-pdf-action@2370f6da4625b181e29e0aedaae32fcaa67064f9 # v1.2.1
        with:
          file1: alternative.pdf
          file2: .ci/reports/alternative.pdf
          options: --verbose --output-diff=alternative-diff.pdf

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@2741064ab9d7af54b0b1ffb6076cf64c16f0220e # v2.2.2
        with:
          dest: docker-logs

      - name: Upload UI Test artifacts
        if: failure()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ui-test-output-${{ matrix.grafana-version }}
          path: |
            test-results
            docker-logs
            default*.pdf
            alternative*.pdf
          retention-days: 1
